version: '2'
services:
    phoenix-app:
        image: phoenix
        external_links:
            - phoenix-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/phoenix?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    phoenix-mysql:
        extends:
            file: mysql.yml
            service: phoenix-mysql
